app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5436/mycar
      password: 'password'
      pool-size: 30
      username: admin

server:
  error:
    include-binding-errors: always
    include-message: always